### PR TITLE
minor changes in text: adapting visual rendering

### PR DESCRIPTION
**Pull request by fintzd**
Hi! 

Just changed the ":::", I think that this is what it was supposed to show (italics or subtitles), but I am not sure, just noticed that it looked weired.

*BTW, as a side-note: great project, love it, I'm browsing your site right now, it is just great! Thank you @libellux !*

### CODE REVIEW

**Review by fintzd — COMMENTED** [review]
Any chance someone checked it out? :)

**Comment by libellux** [comment]
> 
> 
> Any chance someone checked it out? :)

Hello @fintzd sorry for the slow reply been busy with work. Hm the ":::" in vuepress creates collapse. Which browser do you use and could you please provide a screenshot? :)

**Comment by fintzd** [comment]
Hey @libellux ! 

No worries and thank you for the reply in any case! I use Firefox, and attached the screen here! :)

Hope it helps, I'm not sure what the replacement option for that would be good.

Cheers!

Screenshot 2021-07-19 at 13 00 35

**Comment by libellux** [comment]
> 
> 
> Hey @libellux !
> 
> No worries and thank you for the reply in any case! I use Firefox, and attached the screen here! :)
> 
> Hope it helps, I'm not sure what the replacement option for that would be good.
> 
> Cheers!
> 
> Screenshot 2021-07-19 at 13 00 35

Hello @fintzd ! I see you're only viewing the documentation from GitHub - then it might look weird :) if you visit the actual website which is fetched directly from this git you'll see what above markdown does. See attached screenshot.

details

**Pull request closed without merging**
